---
- name: Install repos
  command: "{{ uis_script_path }}"

- name: Install php-fpm y php-mysql
  yum: name={{ item }} 
  with_items:    
    - php56u-fpm
    - php56u-mysql

- name: Copy www.conf file
  template: src=www.conf.j2 dest={{ conf_path }} mode=0644
 
- name: Automatic load when boot
  command: systemctl enable php-fpm.service
  
- name: Be sure php-fpm is running and enable
  service: name=php-fpm state=running enabled=true
  