- name: Install Percona Repository
  yum: name={{ percona_repository }}

- name: Install Percona Server
  yum: name={{ percona_server }} state=present

- name: Automatic load when boot
  command: systemctl enable mysqld.service

- name: Be sure mysqld is running and enable
  service: name=mysqld state=started enabled=true