---
- name: install requirements
  yum: name=$item state=installed
    with_items: 
      - gcc
      - python-devel
      - python-setuptools
      - mysql-devel
        
- name: download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp

- name: install pip
  command: "python /tmp/get-pip.py"

- name: delete get-pip.py
  file: state=absent path=/tmp/get-pip.py

- name: Install the Python MySQLB module
  pip: name=MySQL-python
  
- name: Install Percona Repository
  yum: name={{ percona_repository }}

- name: Install Percona Server
  yum: name={{ percona_server }} state=present

- name: Automatic load when boot
  command: systemctl enable mysqld.service

- name: Be sure mysqld is running and enable
  service: name=mysqld state=running enabled=true

- name: Update mysql root password
  mysql_user: name=root host={{ item }} password={{ root_db_password }} 
  ignore_errors: True
  with_items:   
   - 127.0.0.1
   - ::1
   - localhost
  notify:
   - Restart mysqld.service

- name: Remove anonymous users
  mysql_user: name='' host={{ item }} login_user={{ root_db_user }} login_password={{ root_db_password }} state=absent
  with_items:   
   - 127.0.0.1
   - ::1
   - localhost  

- name: Remove the test database
  mysql_db: name=test login_user={{ root_db_user }} login_password={{ root_db_password }} state=absent