- name: Install Percona Repository
  yum: name={{ percona_repository }}

- name: Install Percona Server
  yum: name={{ percona_server }} state=present

- name: Automatic load when boot
  command: systemctl enable mysqld.service

- name: Be sure mysqld is running and enable
  service: name=mysqld state=running enabled=true

- name: Get temporary pasword
  shell: grep 'temporary password' /var/log/mysqld.log | awk 'END {print $NF}'
  register: temp_root_pass
  
- name: Update mysql root password
  mysql_user: check_implicit_admin=yes
                login_user=root
                login_password={{ temp_root_pass.stdout  }}
                user=root
                password={{ root_db_password }}
                host={{ item }}
  ignore_errors: True
  with_items:   
   - 127.0.0.1
   - ::1
   - localhost
  notify:
   - Restart mysqld.service

- name: Remove anonymous users
  mysql_user: name='' host={{ item }} login_user={{ root_db_user }} login_password={{ root_db_password }} state=absent
  with_items:   
   - 127.0.0.1
   - ::1
   - localhost  

- name: Remove the test database
  mysql_db: name=test login_user={{ root_db_user }} login_password={{ root_db_password }} state=absent