---
- name: Install Nginx Repository
  command: rpm -Uivh --replacepkgs {{nginx_repository}}

- name: Install Nginx
  yum: name=nginx state=latest

- name: Automatic load when boot
  command: systemctl enable nginx.service

- name: Create Folder for default source
  file: path=/srv/www/opencart/grupo04.mosorio.me/html state=directory owner=nginx group=nobody mode=0644

- name: Be sure nginx is running and enable
  service: name=nginx state=running enabled=true
