---
- name: Copy certificate
  template: src=fullchain.pem dest=/etc/pki/tls/certs/ mode=0644

- name: Copy privkey
  template: src=PRIVKEY.pem dest=/etc/pki/tls/private/ mode=0644

- name: Copy default configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/{{ conf_name }}.conf mode=0644
  notify: Restart nginx.service